SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM = 'LATA'

UPDATE [TABELA DE PRODUTOS] SET [PRECO DE LISTA] = [PRECO DE LISTA] * 1.1 WHERE [EMBALAGEM] = 'LATA'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] < 5
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] > 5
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] <= 5
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] >= 5
SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] <> 5

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO]) = 1995 AND [ESTADO] = 'RJ'