CREATE TABLE TABELA_DE_PRODUTOS2(
CODIGO VARCHAR (20),
NOME_PRODUTO VARCHAR (150),
EMBALAGEM VARCHAR (50),
TAMANHO VARCHAR (50),
SABOR VARCHAR (50),
PRECO_DE_LISTA SMALLMONEY
)

DROP TABLE [TABELA_DE_PRODUTOS2]