INSERT INTO [TABELA_DE_PRODUTOS](
CODIGO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA 
) VALUES (
'1037797','clean 2l laranja','pet','2l', 'laranja', 16.01
);

INSERT INTO [TABELA_DE_PRODUTOS](
CODIGO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA 
) VALUES (
'100889','sabor da montanha 2l uva','garrafa','2l', 'uva', 20.00
);

INSERT INTO [TABELA_DE_PRODUTOS](
CODIGO, NOME_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA 
) VALUES (
'100824','guarana 2l guarana','garrafa','2l', 'guarana', 11.90
);

select * from [TABELA_DE_PRODUTOS]


UPDATE [TABELA_DE_PRODUTOS] SET [PRECO_DE_LISTA] = 3 WHERE CODIGO = 104107


DELETE FROM [TABELA_DE_PRODUTOS] WHERE [CODIGO] = 100889


ALTER TABLE [TABELA_DE_PRODUTOS] ALTER  COLUMN [CODIGO] VARCHAR (20) NOT NULL


ALTER TABLE [TABELA_DE_PRODUTOS] ADD CONSTRAINT PK_TABELA_DE_PRODUTOS PRIMARY KEY CLUSTERED ([CODIGO])